site_name: Libtropic SDK Documentation
site_url: https://tropicsquare.github.io/libtropic
repo_url: https://github.com/tropicsquare/libtropic
repo_name: tropicsquare/libtropic
site_description: Official SDK for the TROPIC01 secure element.
site_author: Tropic Square
site_dir: docs_build/

# Theme configuration
theme:
  name: material
  custom_dir: docs/overrides
  font:
    text: Inter
  icon:
    repo: fontawesome/brands/github
  logo: img/TS_logo_white_symbol.svg
  favicon: img/tropic_symbol.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: custom
      # accent: pink
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      # accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      # accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  features:
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - search.suggest
    - content.tabs.link # Allow linking tabs with the same label on a page.

# Navigation menu setup
nav:
  - Introduction: index.md
  - Get Started:
    - get_started/index.md
    - Tutorials:
      - get_started/tutorials/index.md
      - Model:
        - get_started/tutorials/model/index.md
        - 1. Your First Steps: get_started/tutorials/model/first_steps.md
        - 2. Understanding Libtropic: get_started/tutorials/model/understanding_libtropic.md
      - Linux:
        - RPi / Arduino Devkit: get_started/tutorials/linux/arduino_rpi_shield.md
        - USB Devkit: get_started/tutorials/linux/usb_devkit.md
    - Examples:
      - get_started/examples/index.md
      - Linux:
        - Full Chain Verification: get_started/examples/linux/full_chain.md
    - Libtropic Architecture: get_started/libtropic_architecture.md
    - Integrating Libtropic:
      - get_started/integrating_libtropic/index.md
      - How to Build:
        - get_started/integrating_libtropic/how_to_build/index.md
        - Add to an Existing Project: get_started/integrating_libtropic/how_to_build/adding_to_project.md
        - Compile as a Static Library: get_started/integrating_libtropic/how_to_build/compile_as_static_library.md
      - How to Configure: get_started/integrating_libtropic/how_to_configure/index.md
      - How to Use: get_started/integrating_libtropic/how_to_use/index.md
      - Integration Examples: get_started/integrating_libtropic/integration_examples.md
    - TROPIC01 Firmware: get_started/tropic01_fw.md
    - Default Pairing Keys for a Secure Channel Handshake: get_started/default_pairing_keys.md
    - Logging: get_started/logging.md
    - Debugging: get_started/debugging.md
  - API Reference:
    - doxygen/build/html/index.html
  - For Contributors:
    - for_contributors/index.md
    - Contributing Guide: for_contributors/contributing_guide.md
    - Building the Documentation: for_contributors/building_documentation.md
    - Tests:
      - for_contributors/tests/index.md
      - Functional Tests: for_contributors/tests/functional_tests.md
      - Functional Mock Tests: for_contributors/tests/functional_mock_tests.md
      - Code Coverage: for_contributors/tests/code_coverage.md
    - Adding a New Host Platform: for_contributors/adding_host_platform.md
    - Adding a New Cryptographic Functionality Provider: for_contributors/adding_cfp.md
  - FAQ: faq.md
  - Other:
    - other/index.md
    - Provisioning Data: other/provisioning_data.md
    - Supported Host Platforms:
      - other/supported_host_platforms/index.md
      - STM32: other/supported_host_platforms/stm32.md
      - Linux: other/supported_host_platforms/linux.md
      - POSIX: other/supported_host_platforms/posix.md
      - ESP-IDF: other/supported_host_platforms/esp_idf.md
      - Arduino: other/supported_host_platforms/arduino.md
    - Supported Cryptographic Functionality Providers:
      - other/supported_cfps/index.md
      - Trezor Crypto: other/supported_cfps/trezor_crypto.md
      - MbedTLS: other/supported_cfps/mbedtls.md

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      cache_safe: true

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - github-callouts  # Allows GitHub alerts in Markdown
  - pymdownx.snippets:  # Allows to render Markdowns from other directories
      base_path: [!relative $config_dir]
      check_paths: true
  # Following extensions can be used for wider Markdown syntax support
  - admonition
  - pymdownx.arithmatex:    # For math rendering (optional)
      generic: true
  - pymdownx.betterem      # Better emphasis handling
  - pymdownx.caret         # Superscripts
  - pymdownx.critic        # Suggestions / strike-through
  - pymdownx.details       # Collapsible sections
  - pymdownx.emoji:        # Inline icons and emojis
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight     # Extra code highlighting
  - pymdownx.inlinehilite  # Inline code highlighting
  - pymdownx.superfences   # Fenced code blocks
  - pymdownx.tasklist      # Checklists
  - pymdownx.tabbed:       # Tabs. Requires superfences.
      alternate_style: true
  - pymdownx.keys          # Allow rendering of keys (Ctrl, ...) to illustrate shortcuts.

extra:
  version:
    provider: mike
    default: latest  # We use the 'latest' alias here, because we don't know the name of the latest version,
                     # but if we always give the latest version the 'latest' alias,
                     # we don't have to know its name here
    alias: true
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/tropicsquare
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/tropic-square-s-r-o
    - icon: fontawesome/brands/github
      link: https://github.com/tropicsquare/libtropic

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js