name: Run tests against TROPIC01 model
on:
  push:
    branches:
      - 'develop'
      - 'master'
  pull_request:
    branches:
      - 'master'
      - 'develop'
      - 'ETR01SDK-466-New-example-structure-proposal' # TODO remove after verifying functionality

jobs:
  tests_asan:
    name: Run tests with AddressSanitizer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
            sudo apt-get install cmake build-essential
            ./tests/functional/model/download_deps.sh
            ./scripts/tropic01_model/install_linux.sh
            source ./scripts/tropic01_model/.venv/bin/activate
            pip install jsonschema

      - name: Compile libtropic with tests and AddressSanitizer
        run: |
            cd tests/functional/model/
            cmake ./ -B build -G Ninja -DLT_CAL=mbedtls_v4 -DCMAKE_BUILD_TYPE=Debug -DLT_ASAN=1
            cd build/
            ninja

      - name: Execute tests with CTest
        run: |
            cd tests/functional/model/build
            ctest -V
      
      - name: Upload run logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: asan_run_logs
          path: tests/functional/model/build/run_logs

  tests_valgrind:
    name: Run tests with Valgrind
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
            sudo apt-get install cmake build-essential valgrind
            ./tests/functional/model/download_deps.sh
            ./scripts/tropic01_model/install_linux.sh
            source ./scripts/tropic01_model/.venv/bin/activate
            pip install jsonschema

      - name: Compile libtropic with tests and Valgrind
        run: |
            cd tests/functional/model/
            cmake ./ -B build -G Ninja -DLT_CAL=mbedtls_v4 -DCMAKE_BUILD_TYPE=Debug -DLT_VALGRIND=1
            cd build/
            ninja

      - name: Execute tests with CTest
        run: |
            cd tests/functional/model/build
            ctest -V
      
      - name: Upload run logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: valgrind_run_logs
          path: tests/functional/model/build/run_logs