name: Run examples for TROPIC01 model
on:
  push:
    branches:
      - 'develop'
      - 'master'
  pull_request:
    branches:
      - 'master'
      - 'develop'

jobs:
  examples_asan:
    name: Compile and run examples for TROPIC01 model
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
            sudo apt-get install cmake build-essential
            ./tests/functional/model/download_deps.sh
            ./scripts/tropic01_model/install_linux.sh
            source ./scripts/tropic01_model/.venv/bin/activate
            pip install jsonschema

      - name: Compile and run Hello World example
        run: |
            source ./scripts/tropic01_model/.venv/bin/activate
            cd examples/model/hello_world
            cmake ./ -B build -G Ninja ..
            cd build/
            ninja
            python3 ../../../../scripts/tropic01_model/model_runner.py \
              -e ./libtropic_hello_world
              -c ../../../../scripts/tropic01_model/model_cfg.yml
              -o run_logs/
      
      - name: Upload run logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: asan_run_logs
          path: tropic01_model/build/run_logs/
